### ISSUE TITLE
quartus_sh: command not found in GitHub Actions

### ISSUE THREAD

**Issue by mcejp** [chriz2600/quartus-lite#5]
Hello!
I am trying to use this image to run a CI job via GitHub Actions. My workflow is set up like this:

```yaml
  compile-rtl-quartus19:
    runs-on: ubuntu-latest
    container: chriz2600/quartus-lite:19.1.0-2

    steps:
      - uses: actions/checkout@v2

      - name: Compile
        shell: bash
        run: /usr/local/bin/quartus_wrapper quartus_sh --flow compile MyProject
```

However, the CI action fails with the following error:

```
Run /usr/local/bin/quartus_wrapper quartus_sh --flow compile MyProject
/usr/local/bin/quartus_wrapper: line 13: quartus_sh: command not found
Error: Process completed with exit code 127.
```

Presumably, the `/root/.profile.addons` file which extends PATH is not being picked up for some reason. Is there a better work-around than specifying the full path to `quartus_sh` in the workflow file?
